listURL: "https://www.dju.ac.kr/hrc/na/ntt/selectNttList.do"
infoURL: "https://www.dju.ac.kr/hrc/na/ntt/selectNttInfo.do"
downloadURL: "https://www.dju.ac.kr/common/nttFileDownload.do"
bbsId: "2126"
mi: "4597"
